CREATE TABLE IF NOT EXISTS md_insurer_lists (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  display_id INT NOT NULL DEFAULT '0',
  status INT NOT NULL DEFAULT '0',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  logo VARCHAR(255) DEFAULT NULL,
  LOB_type INT NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);
