CREATE TABLE IF NOT EXISTS md_policy_tpas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) DEFAULT NULL,
  tpa_logo_url VARCHAR(150) DEFAULT NULL,
  display_id INT DEFAULT NULL,
  status INT NOT NULL DEFAULT '0',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
