CREATE TABLE IF NOT EXISTS master_add_policies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  corporate_name VARCHAR(100) NOT NULL,
  ref_md_line_of_businesses_id INT NOT NULL,
  line_of_business VARCHAR(100) NOT NULL,
  ref_md_policy_types_id INT NOT NULL,
  policy_type VARCHAR(100) NOT NULL,
  ref_md_sum_insured_types_id INT DEFAULT NULL,
  sum_insured_type VARCHAR(100) DEFAULT NULL,
  ref_select_insurer_id INT NOT NULL,
  select_insurer VARCHAR(255) NOT NULL,
  select_tpa TEXT,
  have_policy_number INT NOT NULL DEFAULT '0',
  policy_number VARCHAR(100) DEFAULT NULL,
  policy_start_date VARCHAR(50) DEFAULT NULL,
  policy_end_date VARCHAR(50) DEFAULT NULL,
  ref_md_family_definitions_id INT DEFAULT NULL,
  family_definition VARCHAR(100) DEFAULT NULL,
  ref_md_claim_submission_visibilities_id INT DEFAULT NULL,
  claim_submission_additional_email TEXT,
  ref_intimate_claim_visibilities_id INT DEFAULT NULL,
  intimate_claim_visibility VARCHAR(50) DEFAULT NULL,
  status INT NOT NULL DEFAULT '0',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  ref_tpa_id INT DEFAULT NULL,
  ref_corporate_id VARCHAR(150) DEFAULT NULL,
  user_id INT DEFAULT NULL,
  ref_fy_year_id INT NOT NULL,
  PRIMARY KEY (id),
  KEY idx_map_status_corp (status, ref_corporate_id, id)
);
