CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) DEFAULT NULL,
  mobile_no VARCHAR(255) NOT NULL,
  email_address VARCHAR(255) NOT NULL,
  password VARCHAR(255) DEFAULT NULL,
  status INT NOT NULL DEFAULT '0',
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  corporate_username VARCHAR(100) DEFAULT NULL,
  employee_code VARCHAR(20) DEFAULT NULL,
  gender VARCHAR(20) DEFAULT NULL,
  dob VARCHAR(20) DEFAULT NULL,
  ref_corporate_id INT DEFAULT NULL,
  ref_md_department_id INT DEFAULT NULL,
  department_name VARCHAR(50) DEFAULT NULL,
  location VARCHAR(100) DEFAULT NULL,
  onboarding_status_id INT DEFAULT '0',
  reporting VARCHAR(100) DEFAULT NULL,
  ref_reporting_id INT DEFAULT NULL,
  designation VARCHAR(100) DEFAULT NULL,
  assign_corporate VARCHAR(100) DEFAULT NULL,
  test_user INT NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);
