CREATE TABLE IF NOT EXISTS master_corporates (
  corporate_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  corporate_name VARCHAR(255) NOT NULL,
  ref_master_logos_corporate_logo INT DEFAULT NULL,
  coporate_contact_email VARCHAR(255) DEFAULT NULL,
  corporate_landline VARCHAR(255) DEFAULT NULL,
  ref_master_pincode_pincode_id INT NOT NULL,
  ref_master_city_city_id INT NOT NULL,
  ref_master_state_state_id INT NOT NULL,
  corporate_address VARCHAR(255) NOT NULL,
  corporate_group_code VARCHAR(255) DEFAULT NULL,
  industry_type VARCHAR(255) DEFAULT NULL,
  branch_name VARCHAR(255) DEFAULT NULL,
  corporate_buffer_visibility INT NOT NULL DEFAULT '0',
  corporate_status INT NOT NULL DEFAULT '0',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  pincode VARCHAR(10) NOT NULL,
  city VARCHAR(25) NOT NULL,
  state VARCHAR(25) NOT NULL,
  helpline_no VARCHAR(255) DEFAULT NULL,
  pan_number VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (corporate_id)
);
